# Generated by Django 5.2.1 on 2025-08-05 22:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('nonce', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('transactions', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=20)),
                ('change_24h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('flag', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('check_box', models.BooleanField(default=False)),
                ('flag', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('private_key', models.TextField(blank=True, null=True, unique=True)),
                ('public_key', models.TextField(blank=True, null=True, unique=True)),
                ('flag', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(default='gift', max_length=20)),
                ('flag', models.IntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='kena', max_length=100)),
                ('type', models.CharField(default='send', max_length=20)),
                ('debit', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash', models.CharField(blank=True, max_length=64, unique=True)),
                ('signature', models.CharField(blank=True, null=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.billing')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('complete', models.BooleanField()),
                ('flag', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=1)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.todolist')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='kena', max_length=100)),
                ('type', models.CharField(default='send', max_length=20)),
                ('debit', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.billing')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('wallettype', models.CharField(default='personal', max_length=20)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('flag', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coin.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.wallet'),
        ),
    ]
