# Generated by Django 5.2.1 on 2025-09-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='type',
            field=models.CharField(default='receive', max_length=20),
        ),
    ]
