# Generated by Django 5.2.1 on 2025-08-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='transactions',
            field=models.JSONField(),
        ),
    ]
