# Generated by Django 5.2.1 on 2025-07-28 00:21

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coin',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='wallet',
            name='Wallettype',
            field=models.CharField(choices=[('personal', 'Personal Wallet'), ('business', 'Business Wallet'), ('miner', 'Miner Wallet')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wallet',
            name='hash',
            field=models.CharField(default=datetime.time(3, 18), max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='passwword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
