# Generated by Django 5.2.6 on 2025-12-12 00:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_paypaltransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='kena', max_length=100)),
                ('type', models.CharField(default='send', max_length=20)),
                ('debit', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('receiver', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash', models.CharField(blank=True, max_length=64, unique=True)),
                ('signature', models.CharField(blank=True, null=True)),
                ('walletHash', models.CharField(blank=True, max_length=200, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.billing')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coin.wallet')),
            ],
        ),
    ]
