# Generated by Django 5.2.6 on 2025-12-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_alter_billing_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
