# Generated by Django 5.2.1 on 2025-09-02 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_block_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='type',
        ),
    ]
