# Generated by Django 5.2.1 on 2025-07-28 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_coin_created_at_coin_flag_coin_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='Wallettype',
            field=models.CharField(default='personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coin.coin'),
        ),
    ]
