# Generated by Django 5.2.1 on 2025-08-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_alter_block_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtransaction',
            name='signature',
            field=models.CharField(blank=True, null=True),
        ),
    ]
