# Generated by Django 5.2.1 on 2025-07-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='check_box',
            field=models.BooleanField(default=False),
        ),
    ]
