# Generated by Django 5.2.1 on 2025-10-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_alter_wallet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.CharField(max_length=64),
        ),
    ]
