# Generated by Django 5.2.6 on 2025-12-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_alter_mpesatransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
