# Generated by Django 5.2.1 on 2025-08-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_alter_pendingtransaction_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='transactions',
        ),
    ]
