# Generated by Django 5.2.1 on 2025-07-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_alter_wallet_wallettype_alter_wallet_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
