# Generated by Django 5.2.6 on 2025-09-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updates_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
