# Generated by Django 5.2.1 on 2025-08-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_remove_block_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='transactions',
            field=models.JSONField(null=True),
        ),
    ]
