# Generated by Django 5.2.1 on 2025-07-28 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_alter_wallet_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='passwword',
            new_name='password',
        ),
    ]
