# Generated by Django 5.2.6 on 2025-12-04 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_alter_transaction_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='buy_kena-mpesa', max_length=20)),
                ('MerchantRequestID', models.CharField(blank=True, max_length=100, null=True)),
                ('CheckoutRequestID', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.billing')),
            ],
        ),
    ]
