# Generated by Django 5.2.6 on 2025-12-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_alter_mpesatransaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='walletHash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='walletHash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
