# Generated by Django 5.2.6 on 2025-09-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0005_customuser_terms_accepted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='updates_accepted',
            new_name='marketing_consent',
        ),
    ]
