# Generated by Django 5.2.6 on 2025-12-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0005_pendingtransaction_wallethash_transaction_wallethash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
