# Generated by Django 5.2.1 on 2025-07-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0006_block_pendingtransaction_billing_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
