# Generated by Django 5.2.6 on 2025-12-06 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0007_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coin.wallet'),
        ),
    ]
