# Generated by Django 5.2.1 on 2025-07-30 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0007_alter_billing_amount_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='Wallettype',
            new_name='wallettype',
        ),
    ]
