# Generated by Django 5.2.1 on 2025-07-30 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0008_rename_wallettype_wallet_wallettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='billing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='coin.billing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
