# Generated by Django 5.2.6 on 2025-12-11 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='buy_kena-paypal', max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.billing')),
            ],
        ),
    ]
